### PR TITLE
Fix oauth2 access: invalid_client_secret

### PR DESCRIPTION
**Pull request by feurigel**
This commits fixes "invalid_client_secret".

The problem was:

- With commit (nextcloud/server@0d112d7#diff-8b87ec33b8bfb6e79af3a46d287408d2) the client_secret was rewrite after reload (or backlink from oauth2) to "\_\_unmodified__"
- To fix this behavior this commit saves client_secret temporary in localstorage
- After reading from localstorage the client_secret would be deleted

Additionally:

- If an user selects onedrive and dropbox or google drive: The plugins overwritten each other's events.

### CODE REVIEW

**Comment by JamesAdams92150** [comment]
when will the merger on develop ?

**Comment by feurigel** [comment]
Sorry, I didn't see that a develop branch exists. I changed the pull request to branch develop.

**Comment by JamesAdams92150** [comment]
I don't no if is Master or develop i'm juste a user and i try to use files_external_onedrive but it's doesn't work :(

**Comment by feurigel** [comment]
> I don't no if is Master or develop i'm juste a user and i try to use files_external_onedrive but it's doesn't work :(

You need to install this plugin manually from here:
https://github.com/feurigel/files_external_onedrive/tree/fix-oauth2-access

Use git clone or download functionality. Warning! The README url is not up-to-date in this repository.
And this plugin doesn't work with Nextcloud 19.

This pull request fixes only #33.

**Pull request merged**
